title: R Workshop
description: An introductory workshop to R programming
theme: just-the-docs

url: https://hms-immunology.github.io/intro-R-workshop

aux_links:
  "Workshop GitHub Repository":
    - "https://hms-immunology.github.io/intro-R-workshop"

# Color scheme
color_scheme: light

# Enable or disable heading anchors
heading_anchors: true 