name: Render R Markdown Files

on:
  push:
    paths:
      - 'class-materials/*.Rmd'
  pull_request:
    paths:
      - 'class-materials/*.Rmd'
  workflow_dispatch:

jobs:
  render:
    runs-on: ubuntu-latest
    container: rocker/verse:latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Create rendered-html directory
        run: mkdir -p rendered-html
      
      - name: Install dependencies
        run: |
          Rscript -e 'install.packages(c(
            "rmarkdown",
            "knitr",
            "tidyverse",
            "viridis",
            "ggplot2",
            "dplyr",
            "tidyr",
            "purrr",
            "readr",
            "forcats",
            "stringr",
            "lubridate",
            "tibble",
            "stats",
            "graphics",
            "grDevices",
            "scales",
            "RColorBrewer"
          ))'
      
      - name: Render R Markdown files
        run: |
          for file in class-materials/*.Rmd
          do
            filename=$(basename "$file" .Rmd)
            Rscript -e "rmarkdown::render('$file', output_format = 'html_document', output_dir = 'rendered-html')"
          done
      
      - name: Commit results
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add rendered-html/*.html
          git commit -m "Re-render R Markdown files" || echo "No changes to commit"
          git push origin || echo "No changes to push" 